import type { AttributeMultipliersType } from '@schemas/EvAns.zod.ts';


export const PvPAttackAttributeMultipliers: AttributeMultipliersType =
  {
    AttackingAttackDebuff: {
      ReduceAllAttack: 2,
      ReduceEnemyGroundAttack: 0.5,
      ReduceEnemyMountedAttack: 0.5,
      ReduceEnemyRangedAttack: 0.5,
      ReduceEnemySiegeAttack: 0.5,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 2,
      ReduceEnemyAllHP: 2,
      ReduceEnemyGroundDefense: 0.5,
      ReduceEnemyGroundHP: 0.5,
      ReduceEnemyMountedDefense: 0.5,
      ReduceEnemyMountedHP: 0.5,
      ReduceEnemyRangedDefense: 0.5,
      ReduceEnemyRangedHP: 0.5,
      ReduceEnemySiegeDefense: 0.5,
      ReduceEnemySiegeHP: 0.5,
    },
    Debilitation: {
      InCityWounded2Death: 0.1,
      Wounded2Death: 0.1,
      Wounded2DeathWhenAttacking: 0.1,
    },
    Offensive: {
      AllTroopAttack: 4,
      GroundAttack: 1,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 1,
      MountedAttack: 1,
      RallyCapacity: 0.5,
      RangedAttack: 1,
      RangedRangeBonus: 1,
      SiegeAttack: 1,
      SiegeRangeBonusFlat: 1,
      SiegeRangeBonusPercent: 1,
    },
    Preservation: {
      Death2Souls: 0.1,
      Death2SoulsinMainCity: 0,
      Death2Wounded: 0.1,
      Death2WoundedWhenAttacking: 0.1,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 2,
      ReduceEnemyGroundAttack: 0.5,
      ReduceEnemyMountedAttack: 0.5,
      ReduceEnemyRangedAttack: 0.5,
      ReduceEnemySiegeAttack: 0.5,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 2,
      ReduceEnemyAllHP: 2,
      ReduceEnemyGroundDefense: 0.5,
      ReduceEnemyGroundHP: 0.5,
      ReduceEnemyMountedDefense: 0.5,
      ReduceEnemyMountedHP: 0.5,
      ReduceEnemyRangedDefense: 0.5,
      ReduceEnemyRangedHP: 0.5,
      ReduceEnemySiegeDefense: 0.5,
      ReduceEnemySiegeHP: 0.5,
    },
    Toughness: {
      AllTroopDefense: 2,
      AllTroopHP: 0.5,
      GroundDefense: 0.5,
      GroundHP: 0.5,
      MountedDefense: 0.5,
      MountedHP: 0.5,
      RangedDefense: 0.5,
      RangedHP: 0.5,
      SiegeDefense: 0.5,
      SiegeHP: 0.5,
    },
  };

export const PvPReinforcementAttributeMultipliers: AttributeMultipliersType =
  {
    AttackingAttackDebuff: {
      ReduceAllAttack: 0,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 0,
      ReduceEnemyAllHP: 0,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    Debilitation: {
      Wounded2Death: 0.1,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
    Offensive: {
      AllTroopAttack: 4,
      GroundAttack: 1,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 1,
      MountedAttack: 1,
      RallyCapacity: 0,
      RangedAttack: 1,
      RangedRangeBonus: 1,
      SiegeAttack: 1,
      SiegeRangeBonusFlat: 1,
      SiegeRangeBonusPercent: 1,
    },
    Preservation: {
      Death2Wounded: 0.1,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0.1,
      Death2SoulsinMainCity: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 2,
      ReduceEnemyGroundAttack: 0.5,
      ReduceEnemyMountedAttack: 0.5,
      ReduceEnemyRangedAttack: 0.5,
      ReduceEnemySiegeAttack: 0.5,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 2,
      ReduceEnemyAllHP: 2,
      ReduceEnemyGroundDefense: 0.5,
      ReduceEnemyGroundHP: 0.5,
      ReduceEnemyMountedDefense: 0.5,
      ReduceEnemyMountedHP: 0.5,
      ReduceEnemyRangedDefense: 0.5,
      ReduceEnemyRangedHP: 0.5,
      ReduceEnemySiegeDefense: 0.5,
      ReduceEnemySiegeHP: 0.5,
    },
    Toughness: {
      AllTroopDefense: 4,
      AllTroopHP: 4,
      GroundDefense: 1,
      GroundHP: 1,
      MountedDefense: 1,
      MountedHP: 1,
      RangedDefense: 1,
      RangedHP: 1,
      SiegeDefense: 1,
      SiegeHP: 1,
    },
  };


export const MayorPvPAttackAttributeMultipliers: AttributeMultipliersType =
  {
    AttackingAttackDebuff: {
      ReduceAllAttack: 4,
      ReduceEnemyMountedAttack: 1,
      ReduceEnemyRangedAttack: 1,
      ReduceEnemySiegeAttack: 1,
      ReduceEnemyGroundAttack: 1,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllHP: 4,
      ReduceEnemyRangedHP: 1,
      ReduceEnemySiegeHP: 1,
      ReduceEnemyMountedHP: 1,
      ReduceEnemyGroundHP: 1,
      ReduceEnemyAllDefense: 4,
      ReduceEnemyRangedDefense: 1,
      ReduceEnemySiegeDefense: 1,
      ReduceEnemyMountedDefense: 1,
      ReduceEnemyGroundDefense: 1,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
    Offensive: {
      AllTroopAttack: .25,
      GroundAttack: 0.125,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0.125,
      RallyCapacity: 0,
      RangedAttack: 0.125,
      RangedRangeBonus: 0.125,
      SiegeAttack: 0,
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 4,
      ReduceEnemyMountedAttack: 1,
      ReduceEnemyRangedAttack: 1,
      ReduceEnemySiegeAttack: 1,
      ReduceEnemyGroundAttack: 1,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllHP: 4,
      ReduceEnemyRangedHP: 1,
      ReduceEnemySiegeHP: 1,
      ReduceEnemyMountedHP: 1,
      ReduceEnemyGroundHP: 1,
      ReduceEnemyAllDefense: 4,
      ReduceEnemyRangedDefense: 1,
      ReduceEnemySiegeDefense: 1,
      ReduceEnemyMountedDefense: 1,
      ReduceEnemyGroundDefense: 1,
    },
    Toughness: {
      AllTroopHP: .5,
      RangedHP: 0.25,
      MountedHP: 0.25,
      GroundHP: 0.25,
      SiegeHP: 0,
      AllTroopDefense: 0.5,
      RangedDefense: 0.25,
      MountedDefense: 0.25,
      SiegeDefense: 0,
      GroundDefense: 0.25,
    },
  };

export const MayorAttackArchersAttributeMultipliers: AttributeMultipliersType =
  {
    Offensive: {
      AllTroopAttack: 0.0625,
      GroundAttack: 0,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0,
      RallyCapacity: 0,
      RangedAttack: 0.031250,
      RangedRangeBonus: 0.031250,
      SiegeAttack: 0,
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Toughness: {
      AllTroopDefense: 0.1250,
      AllTroopHP: 0.1250,
      GroundDefense: 0,
      GroundHP: 0,
      MountedDefense: 0,
      MountedHP: 0,
      RangedDefense: 0.0625,
      RangedHP: 0.0625,
      SiegeDefense: 0,
      SiegeHP: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    AttackingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 1,
      ReduceEnemySiegeAttack: 0,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 1,
      ReduceEnemyRangedHP: 1,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 1,
      ReduceEnemySiegeAttack: 0,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 1,
      ReduceEnemyRangedHP: 1,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
  };

export const MayorAttackGroundAttributeMultipliers: AttributeMultipliersType =
  {
    Offensive: {
      AllTroopAttack: 0.0625,
      GroundAttack: 0.031250,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0,
      RallyCapacity: 0,
      RangedAttack: 0,
      RangedRangeBonus: 0,
      SiegeAttack: 0,
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Toughness: {
      AllTroopDefense: 0.1250,
      AllTroopHP: 0.1250,
      GroundDefense: 0.0625,
      GroundHP: 0.0625,
      MountedDefense: 0,
      MountedHP: 0,
      RangedDefense: 0,
      RangedHP: 0,
      SiegeDefense: 0,
      SiegeHP: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    AttackingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 1,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 1,
      ReduceEnemyGroundHP: 1,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 1,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 1,
      ReduceEnemyGroundHP: 1,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
  };

export const MayorAttackMountedAttributeMultipliers: AttributeMultipliersType =
  {
    Offensive: {
      AllTroopAttack: 0.0625,
      GroundAttack: 0,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0.031250,
      RallyCapacity: 0,
      RangedAttack: 0,
      RangedRangeBonus: 0,
      SiegeAttack: 0,
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Toughness: {
      AllTroopDefense: 0.1250,
      AllTroopHP: 0.1250,
      GroundDefense: 0,
      GroundHP: 0,
      MountedDefense: 0.0625,
      MountedHP: 0.0625,
      RangedDefense: 0,
      RangedHP: 0,
      SiegeDefense: 0,
      SiegeHP: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    AttackingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 1,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 1,
      ReduceEnemyMountedHP: 1,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 1,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 1,
      ReduceEnemyMountedHP: 1,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
  };

export const MayorAttackSiegeAttributeMultipliers: AttributeMultipliersType =
  {
    Offensive: {
      AllTroopAttack: 0.0625,
      GroundAttack: 0,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0,
      RallyCapacity: 0,
      RangedAttack: 0,
      RangedRangeBonus: 0,
      SiegeAttack: 0, //subs have no siege
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Toughness: {
      AllTroopDefense: 0.1250,
      AllTroopHP: 0.1250,
      GroundDefense: 0,
      GroundHP: 0,
      MountedDefense: 0,
      MountedHP: 0,
      RangedDefense: 0,
      RangedHP: 0,
      SiegeDefense: 0, //subs have no siege
      SiegeHP: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    AttackingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 1,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 1,
      ReduceEnemySiegeHP: 1,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 1,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 1,
      ReduceEnemySiegeHP: 1,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
  };
