baseURL = 'https://www.evonytkrtips.net/'
languageCode = 'en-us'
title = 'Evony TKR Tips'
theme = ['spectrum']

tags = []

[author]
  name = "Luke Schierer"
  homepage = "https://www.schierer.org/~luke"