name = "Evony TKR Tips"
license = "MIT"
licenselink = "http://creativecommons.org/licenses/by-nc/4.0/"
description = "Tips for Budget Gamers"

homepage = "https://evonytkrtips.net/"

tags = []

[author]
  name = "Luke Schierer"
  homepage = "https://www.schierer.org/~luke"
