import type { AttributeMultipliersType } from '@schemas/EvAns.zod.ts';

export const MayorPvPAttackAttributeMultipliers: AttributeMultipliersType = {
  Offensive: {
    AllTroopAttack: 0.25,
    GroundAttack: 0.125,
    RangedAttack: 0.125,
    SiegeAttack: 0,
    MountedAttack: 0.125,
    InBattleMovementBonus: 0,
    MarchSizeIncrease: 0,
    RallyCapacity: 0,
    RangedRangeBonus: 0.125,
    SiegeRangeBonusFlat: 0,
    SiegeRangeBonusPercent: 0,
  },
  Toughness: {
    AllTroopHP: 0.5,
    RangedHP: 0.25,
    MountedHP: 0.25,
    GroundHP: 0.25,
    SiegeHP: 0,
    AllTroopDefense: 0.5,
    RangedDefense: 0.25,
    MountedDefense: 0.25,
    SiegeDefense: 0,
    GroundDefense: 0.25,
  },
  Preservation: {
    Death2Wounded: 0,
    Death2WoundedWhenAttacking: 0,
    Death2Souls: 0,
    Death2SoulsinMainCity: 0,
  },
  AttackingAttackDebuff: {
    ReduceAllAttack: 4,
    ReduceEnemyMountedAttack: 1,
    ReduceEnemyRangedAttack: 1,
    ReduceEnemySiegeAttack: 1,
    ReduceEnemyGroundAttack: 1,
  },
  AttackingToughnessDebuff: {
    ReduceEnemyAllHP: 4,
    ReduceEnemyRangedHP: 1,
    ReduceEnemySiegeHP: 1,
    ReduceEnemyMountedHP: 1,
    ReduceEnemyGroundHP: 1,
    ReduceEnemyAllDefense: 4,
    ReduceEnemyRangedDefense: 1,
    ReduceEnemySiegeDefense: 1,
    ReduceEnemyMountedDefense: 1,
    ReduceEnemyGroundDefense: 1,
  },
  ReinforcingAttackDebuff: {
    ReduceAllAttack: 4,
    ReduceEnemyMountedAttack: 1,
    ReduceEnemyRangedAttack: 1,
    ReduceEnemySiegeAttack: 1,
    ReduceEnemyGroundAttack: 1,
  },
  ReinforcingToughnessDebuff: {
    ReduceEnemyAllHP: 4,
    ReduceEnemyRangedHP: 1,
    ReduceEnemySiegeHP: 1,
    ReduceEnemyMountedHP: 1,
    ReduceEnemyGroundHP: 1,
    ReduceEnemyAllDefense: 4,
    ReduceEnemyRangedDefense: 1,
    ReduceEnemySiegeDefense: 1,
    ReduceEnemyMountedDefense: 1,
    ReduceEnemyGroundDefense: 1,
  },
  Debilitation: {
    Wounded2Death: 0,
    InCityWounded2Death: 0,
    Wounded2DeathWhenAttacking: 0,
  },
};

export const MayorGroundAttackAttributeMultipliers: AttributeMultipliersType = {
  Offensive: {
    AllTroopAttack: 0.0625,
    GroundAttack: 0.03125,
    InBattleMovementBonus: 0,
    MarchSizeIncrease: 0,
    MountedAttack: 0,
    RallyCapacity: 0,
    RangedAttack: 0,
    RangedRangeBonus: 0,
    SiegeAttack: 0,
    SiegeRangeBonusFlat: 0,
    SiegeRangeBonusPercent: 0,
  },
  Toughness: {
    AllTroopDefense: 0.125,
    AllTroopHP: 0.125,
    GroundDefense: 0.0625,
    GroundHP: 0.0625,
    MountedDefense: 0,
    MountedHP: 0,
    RangedDefense: 0,
    RangedHP: 0,
    SiegeDefense: 0,
    SiegeHP: 0,
  },
  Preservation: {
    Death2Wounded: 0,
    Death2WoundedWhenAttacking: 0,
    Death2Souls: 0,
    Death2SoulsinMainCity: 0,
  },
  AttackingAttackDebuff: {
    ReduceAllAttack: 1,
    ReduceEnemyGroundAttack: 1,
    ReduceEnemyMountedAttack: 0,
    ReduceEnemyRangedAttack: 0,
    ReduceEnemySiegeAttack: 0,
  },
  AttackingToughnessDebuff: {
    ReduceEnemyAllDefense: 1,
    ReduceEnemyAllHP: 1,
    ReduceEnemyGroundDefense: 1,
    ReduceEnemyGroundHP: 1,
    ReduceEnemyMountedDefense: 0,
    ReduceEnemyMountedHP: 0,
    ReduceEnemyRangedDefense: 0,
    ReduceEnemyRangedHP: 0,
    ReduceEnemySiegeDefense: 0,
    ReduceEnemySiegeHP: 0,
  },
  ReinforcingAttackDebuff: {
    ReduceAllAttack: 1,
    ReduceEnemyGroundAttack: 1,
    ReduceEnemyMountedAttack: 0,
    ReduceEnemyRangedAttack: 0,
    ReduceEnemySiegeAttack: 0,
  },
  ReinforcingToughnessDebuff: {
    ReduceEnemyAllDefense: 1,
    ReduceEnemyAllHP: 1,
    ReduceEnemyGroundDefense: 1,
    ReduceEnemyGroundHP: 1,
    ReduceEnemyMountedDefense: 0,
    ReduceEnemyMountedHP: 0,
    ReduceEnemyRangedDefense: 0,
    ReduceEnemyRangedHP: 0,
    ReduceEnemySiegeDefense: 0,
    ReduceEnemySiegeHP: 0,
  },
  Debilitation: {
    Wounded2Death: 0,
    InCityWounded2Death: 0,
    Wounded2DeathWhenAttacking: 0,
  },
};

export const MayorArchersAttackAttributeMultipliers: AttributeMultipliersType =
  {
    Offensive: {
      AllTroopAttack: 0.0625,
      GroundAttack: 0,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0,
      RallyCapacity: 0,
      RangedAttack: 0.03125,
      RangedRangeBonus: 0.03125,
      SiegeAttack: 0,
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Toughness: {
      AllTroopDefense: 0.125,
      AllTroopHP: 0.125,
      GroundDefense: 0,
      GroundHP: 0,
      MountedDefense: 0,
      MountedHP: 0,
      RangedDefense: 0.0625,
      RangedHP: 0.0625,
      SiegeDefense: 0,
      SiegeHP: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    AttackingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 1,
      ReduceEnemySiegeAttack: 0,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 1,
      ReduceEnemyRangedHP: 1,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 0,
      ReduceEnemyRangedAttack: 1,
      ReduceEnemySiegeAttack: 0,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 0,
      ReduceEnemyMountedHP: 0,
      ReduceEnemyRangedDefense: 1,
      ReduceEnemyRangedHP: 1,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
  };

export const MayorMountedAttackAttributeMultipliers: AttributeMultipliersType =
  {
    Offensive: {
      AllTroopAttack: 0.0625,
      GroundAttack: 0,
      InBattleMovementBonus: 0,
      MarchSizeIncrease: 0,
      MountedAttack: 0.03125,
      RallyCapacity: 0,
      RangedAttack: 0,
      RangedRangeBonus: 0,
      SiegeAttack: 0,
      SiegeRangeBonusFlat: 0,
      SiegeRangeBonusPercent: 0,
    },
    Toughness: {
      AllTroopDefense: 0.125,
      AllTroopHP: 0.125,
      GroundDefense: 0,
      GroundHP: 0,
      MountedDefense: 0.0625,
      MountedHP: 0.0625,
      RangedDefense: 0,
      RangedHP: 0,
      SiegeDefense: 0,
      SiegeHP: 0,
    },
    Preservation: {
      Death2Wounded: 0,
      Death2WoundedWhenAttacking: 0,
      Death2Souls: 0,
      Death2SoulsinMainCity: 0,
    },
    AttackingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 1,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    AttackingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 1,
      ReduceEnemyMountedHP: 1,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    ReinforcingAttackDebuff: {
      ReduceAllAttack: 1,
      ReduceEnemyGroundAttack: 0,
      ReduceEnemyMountedAttack: 1,
      ReduceEnemyRangedAttack: 0,
      ReduceEnemySiegeAttack: 0,
    },
    ReinforcingToughnessDebuff: {
      ReduceEnemyAllDefense: 1,
      ReduceEnemyAllHP: 1,
      ReduceEnemyGroundDefense: 0,
      ReduceEnemyGroundHP: 0,
      ReduceEnemyMountedDefense: 1,
      ReduceEnemyMountedHP: 1,
      ReduceEnemyRangedDefense: 0,
      ReduceEnemyRangedHP: 0,
      ReduceEnemySiegeDefense: 0,
      ReduceEnemySiegeHP: 0,
    },
    Debilitation: {
      Wounded2Death: 0,
      InCityWounded2Death: 0,
      Wounded2DeathWhenAttacking: 0,
    },
  };

export const MayorSiegeAttackAttributeMultipliers: AttributeMultipliersType = {
  Offensive: {
    AllTroopAttack: 0.0625,
    GroundAttack: 0,
    InBattleMovementBonus: 0,
    MarchSizeIncrease: 0,
    MountedAttack: 0,
    RallyCapacity: 0,
    RangedAttack: 0,
    RangedRangeBonus: 0,
    SiegeAttack: 0, //subs have no siege
    SiegeRangeBonusFlat: 0,
    SiegeRangeBonusPercent: 0,
  },
  Toughness: {
    AllTroopDefense: 0.125,
    AllTroopHP: 0.125,
    GroundDefense: 0,
    GroundHP: 0,
    MountedDefense: 0,
    MountedHP: 0,
    RangedDefense: 0,
    RangedHP: 0,
    SiegeDefense: 0, //subs have no siege
    SiegeHP: 0,
  },
  Preservation: {
    Death2Wounded: 0,
    Death2WoundedWhenAttacking: 0,
    Death2Souls: 0,
    Death2SoulsinMainCity: 0,
  },
  AttackingAttackDebuff: {
    ReduceAllAttack: 1,
    ReduceEnemyGroundAttack: 0,
    ReduceEnemyMountedAttack: 0,
    ReduceEnemyRangedAttack: 0,
    ReduceEnemySiegeAttack: 1,
  },
  AttackingToughnessDebuff: {
    ReduceEnemyAllDefense: 1,
    ReduceEnemyAllHP: 1,
    ReduceEnemyGroundDefense: 0,
    ReduceEnemyGroundHP: 0,
    ReduceEnemyMountedDefense: 0,
    ReduceEnemyMountedHP: 0,
    ReduceEnemyRangedDefense: 0,
    ReduceEnemyRangedHP: 0,
    ReduceEnemySiegeDefense: 1,
    ReduceEnemySiegeHP: 1,
  },
  ReinforcingAttackDebuff: {
    ReduceAllAttack: 1,
    ReduceEnemyGroundAttack: 0,
    ReduceEnemyMountedAttack: 0,
    ReduceEnemyRangedAttack: 0,
    ReduceEnemySiegeAttack: 1,
  },
  ReinforcingToughnessDebuff: {
    ReduceEnemyAllDefense: 1,
    ReduceEnemyAllHP: 1,
    ReduceEnemyGroundDefense: 0,
    ReduceEnemyGroundHP: 0,
    ReduceEnemyMountedDefense: 0,
    ReduceEnemyMountedHP: 0,
    ReduceEnemyRangedDefense: 0,
    ReduceEnemyRangedHP: 0,
    ReduceEnemySiegeDefense: 1,
    ReduceEnemySiegeHP: 1,
  },
  Debilitation: {
    Wounded2Death: 0,
    InCityWounded2Death: 0,
    Wounded2DeathWhenAttacking: 0,
  },
};
